"""empty message

Revision ID: 06c0983a8581
Revises: 5650b443e158
Create Date: 2025-04-14 09:30:51.890078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c0983a8581'
down_revision = '5650b443e158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_compra', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('proveedor', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('numero_factura', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('capacidad_maxima', sa.Integer(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('capacidad_maxima')
        batch_op.drop_column('ubicacion')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stock_id')

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('estado')
        batch_op.drop_column('total')
        batch_op.drop_column('numero_factura')
        batch_op.drop_column('proveedor')
        batch_op.drop_column('fecha_compra')

    # ### end Alembic commands ###
