"""empty message

Revision ID: 1a1dbaaee86a
Revises: d1b07d1ea297
Create Date: 2025-04-16 08:09:49.399795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1dbaaee86a'
down_revision = 'd1b07d1ea297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'rol', ['rol_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stock_id')

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rol_id')

    # ### end Alembic commands ###
