"""empty message

Revision ID: 2712ebdea603
Revises: c5e229b408c3
Create Date: 2025-04-14 18:23:56.923277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2712ebdea603'
down_revision = 'c5e229b408c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.drop_constraint('logo_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('productos_stock_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('productos_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('stock_id')

    with op.batch_alter_table('tigris_files', schema=None) as batch_op:
        batch_op.drop_constraint('tigris_files_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tigris_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tigris_files_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('productos_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('productos_stock_id_fkey', 'stock', ['stock_id'], ['id'])

    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('logo_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
