"""empty message

Revision ID: 47461994a984
Revises: c3e6a046abd5
Create Date: 2025-04-22 11:08:21.950569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47461994a984'
down_revision = 'c3e6a046abd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageurl', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_column('imageurl')

    # ### end Alembic commands ###
