"""empty message

Revision ID: 5d5e62863d5e
Revises: 47461994a984
Create Date: 2025-04-22 11:10:25.686030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5e62863d5e'
down_revision = '47461994a984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logourl', sa.String(length=500), nullable=True))
        batch_op.drop_column('imageurl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageurl', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('logourl')

    # ### end Alembic commands ###
