"""empty message

Revision ID: 86f54b83fbe7
Revises: f7867099bb50
Create Date: 2025-04-22 09:34:29.003072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f54b83fbe7'
down_revision = 'f7867099bb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storename', sa.String(length=120), nullable=False),
    sa.Column('storeemail', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('bankaccount', sa.String(length=24), nullable=False),
    sa.Column('theme', sa.String(length=25), nullable=False),
    sa.Column('shopurl', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopurl'),
    sa.UniqueConstraint('storeemail'),
    sa.UniqueConstraint('storename')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyed', sa.Boolean(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('compras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='compras_pkey')
    )
    op.drop_table('cart')
    op.drop_table('shop')
    # ### end Alembic commands ###
