"""empty message

Revision ID: 86faa73f07a1
Revises: 86f54b83fbe7
Create Date: 2025-04-22 09:42:49.862963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86faa73f07a1'
down_revision = '86f54b83fbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cart_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
