"""empty message

Revision ID: 943d2996fa22
Revises: 1a1dbaaee86a
Create Date: 2025-04-16 08:39:23.595319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943d2996fa22'
down_revision = '1a1dbaaee86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'rol', ['rol_id'], ['id'])

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compras_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'compras', ['compras_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('compras_id')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rol_id')

    # ### end Alembic commands ###
