"""empty message

Revision ID: c5e229b408c3
Revises: 06c0983a8581
Create Date: 2025-04-14 09:52:55.110439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e229b408c3'
down_revision = '06c0983a8581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_factura', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('fecha_emision', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cliente_nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('cliente_direccion', sa.String(length=350), nullable=True))
        batch_op.add_column(sa.Column('cliente_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cliente_telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cif_cliente', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('impuestos', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('notas', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint(None, ['num_factura'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('notas')
        batch_op.drop_column('estado')
        batch_op.drop_column('total')
        batch_op.drop_column('impuestos')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('cif_cliente')
        batch_op.drop_column('cliente_telefono')
        batch_op.drop_column('cliente_email')
        batch_op.drop_column('cliente_direccion')
        batch_op.drop_column('cliente_nombre')
        batch_op.drop_column('fecha_vencimiento')
        batch_op.drop_column('fecha_emision')
        batch_op.drop_column('num_factura')

    # ### end Alembic commands ###
