"""empty message

Revision ID: eb988b792891
Revises: 943d2996fa22
Create Date: 2025-04-16 09:09:55.558299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb988b792891'
down_revision = '943d2996fa22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=350), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('cif', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cif_empresa', sa.String(length=50), nullable=False))

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('cliente_direccion')
        batch_op.drop_column('cif_empresa')
        batch_op.drop_column('cif_cliente')
        batch_op.drop_column('cliente_email')
        batch_op.drop_column('cliente_nombre')
        batch_op.drop_column('cliente_telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cliente_nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cliente_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cif_cliente', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cif_empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cliente_direccion', sa.VARCHAR(length=350), autoincrement=False, nullable=True))

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('cif_empresa')

    op.drop_table('cliente')
    # ### end Alembic commands ###
